CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "Users" (
        "Id" text NOT NULL,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "Username" text NULL,
        "Image" text NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "Categories" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "UserId" text NULL,
        "Updated" timestamp without time zone NOT NULL,
        "Slug" text NULL,
        "Version" integer NOT NULL,
        "State" integer NOT NULL,
        "Name" text NULL,
        "Description" text NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "Difficulties" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "UserId" text NULL,
        "Updated" timestamp without time zone NOT NULL,
        "Slug" text NULL,
        "Version" integer NOT NULL,
        "State" integer NOT NULL,
        "Name" text NULL,
        "Description" text NULL,
        CONSTRAINT "PK_Difficulties" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Difficulties_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "ModerationItems" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "UserId" text NULL,
        "Updated" timestamp without time zone NOT NULL,
        "Current" integer NOT NULL,
        "Target" integer NOT NULL,
        "Type" text NULL,
        "Reason" text NULL,
        "Rejected" boolean NOT NULL,
        CONSTRAINT "PK_ModerationItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ModerationItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "Submissions" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "TrickId" text NULL,
        "VideoProcessed" boolean NOT NULL,
        "Description" text NULL,
        "UserId" text NULL,
        CONSTRAINT "PK_Submissions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Submissions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "Tricks" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "UserId" text NULL,
        "Updated" timestamp without time zone NOT NULL,
        "Slug" text NULL,
        "Version" integer NOT NULL,
        "State" integer NOT NULL,
        "Name" text NULL,
        "Description" text NULL,
        CONSTRAINT "PK_Tricks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tricks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "Reviews" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "UserId" text NULL,
        "Updated" timestamp without time zone NOT NULL,
        "ModerationItemId" integer NOT NULL,
        "Comment" text NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reviews_ModerationItems_ModerationItemId" FOREIGN KEY ("ModerationItemId") REFERENCES "ModerationItems" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "Comments" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "Content" text NULL,
        "HtmlContent" text NULL,
        "ModerationItemId" integer NULL,
        "SubmissionId" integer NULL,
        "ParentId" integer NULL,
        "UserId" text NULL,
        CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Comments_ModerationItems_ModerationItemId" FOREIGN KEY ("ModerationItemId") REFERENCES "ModerationItems" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Comments_Comments_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Comments" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Comments_Submissions_SubmissionId" FOREIGN KEY ("SubmissionId") REFERENCES "Submissions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "SubmissionVotes" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "UserId" text NULL,
        "Updated" timestamp without time zone NOT NULL,
        "SubmissionId" integer NOT NULL,
        "Value" integer NOT NULL,
        CONSTRAINT "PK_SubmissionVotes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SubmissionVotes_Submissions_SubmissionId" FOREIGN KEY ("SubmissionId") REFERENCES "Submissions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SubmissionVotes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "Videos" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Deleted" boolean NOT NULL,
        "Created" timestamp without time zone NOT NULL,
        "SubmissionId" integer NULL,
        "VideoLink" text NULL,
        "ThumbLink" text NULL,
        CONSTRAINT "PK_Videos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Videos_Submissions_SubmissionId" FOREIGN KEY ("SubmissionId") REFERENCES "Submissions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "TrickCategories" (
        "TrickId" integer NOT NULL,
        "CategoryId" integer NOT NULL,
        "Active" boolean NOT NULL,
        CONSTRAINT "PK_TrickCategories" PRIMARY KEY ("CategoryId", "TrickId"),
        CONSTRAINT "FK_TrickCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TrickCategories_Tricks_TrickId" FOREIGN KEY ("TrickId") REFERENCES "Tricks" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "TrickDifficulties" (
        "TrickId" integer NOT NULL,
        "DifficultyId" integer NOT NULL,
        "Active" boolean NOT NULL,
        CONSTRAINT "PK_TrickDifficulties" PRIMARY KEY ("DifficultyId", "TrickId"),
        CONSTRAINT "FK_TrickDifficulties_Difficulties_DifficultyId" FOREIGN KEY ("DifficultyId") REFERENCES "Difficulties" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TrickDifficulties_Tricks_TrickId" FOREIGN KEY ("TrickId") REFERENCES "Tricks" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE TABLE "TrickRelationships" (
        "PrerequisiteId" integer NOT NULL,
        "ProgressionId" integer NOT NULL,
        "Active" boolean NOT NULL,
        CONSTRAINT "PK_TrickRelationships" PRIMARY KEY ("PrerequisiteId", "ProgressionId"),
        CONSTRAINT "FK_TrickRelationships_Tricks_PrerequisiteId" FOREIGN KEY ("PrerequisiteId") REFERENCES "Tricks" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TrickRelationships_Tricks_ProgressionId" FOREIGN KEY ("ProgressionId") REFERENCES "Tricks" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Categories_UserId" ON "Categories" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Comments_ModerationItemId" ON "Comments" ("ModerationItemId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Comments_ParentId" ON "Comments" ("ParentId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Comments_SubmissionId" ON "Comments" ("SubmissionId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Difficulties_UserId" ON "Difficulties" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_ModerationItems_UserId" ON "ModerationItems" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Reviews_ModerationItemId" ON "Reviews" ("ModerationItemId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Reviews_UserId" ON "Reviews" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Submissions_UserId" ON "Submissions" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_SubmissionVotes_SubmissionId" ON "SubmissionVotes" ("SubmissionId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_SubmissionVotes_UserId" ON "SubmissionVotes" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_TrickCategories_TrickId" ON "TrickCategories" ("TrickId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_TrickDifficulties_TrickId" ON "TrickDifficulties" ("TrickId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_TrickRelationships_ProgressionId" ON "TrickRelationships" ("ProgressionId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE INDEX "IX_Tricks_UserId" ON "Tricks" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    CREATE UNIQUE INDEX "IX_Videos_SubmissionId" ON "Videos" ("SubmissionId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201120143613_init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201120143613_init', '3.1.9');
    END IF;
END $$;
